sudo: required
services:
  - docker

before_install:
  - docker build -t theprotos/docker-react -f on-prem/simple-react/Dockerfile.dev on-prem/simple-react

script:
  - docker run -e CI=true theprotos/docker-react npm run test -- --coverage
